---
title: "Proj 2"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* Import data
```{r}
image1 = read.delim(file = "image_data/image1.txt", header = FALSE, sep = "")
colnames(image1) = c("y_coord", "x_coord", "expert_label", "NDAI", "SD", "CORR", "DF", "CF", "BF", "AF", "AN")
image2 = read.delim(file = "image_data/image2.txt", header = FALSE, sep = "")
colnames(image2) = c("y_coord", "x_coord", "expert_label", "NDAI", "SD", "CORR", "DF", "CF", "BF", "AF", "AN")
image3 = read.delim(file = "image_data/image3.txt", header = FALSE, sep = "")
colnames(image3) = c("y_coord", "x_coord", "expert_label", "NDAI", "SD", "CORR", "DF", "CF", "BF", "AF", "AN")
all = rbind(image1, image2, image3)
```


* 1(b)
```{r}
sum(all$expert_label == 1) / nrow(all)
sum(all$expert_label == -1) / nrow(all)
sum(all$expert_label == 0) / nrow(all)
```
After we combined three image data sets, we calculate % of pixels for the different classes: 23.43% classified as cloud, 36.78% classified as 
